# Generated by Django 4.0.3 on 2022-12-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
